name: eazio
description: "Task App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: ^4.6.6
  flutter_svg: any
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  countup: ^0.1.4
  google_maps_flutter:
  custom_info_window: ^1.0.1
  widget_to_marker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.otf
          weight: 700
        - asset: assets/fonts/InterMedium.otf
          weight: 400
        - asset: assets/fonts/InterRegular.otf
          weight: 300
        - asset: assets/fonts/InterSemiBold.otf
          weight: 600